# Generated by Django 5.0.4 on 2024-04-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_subject_data_blooms_level_subject_data_bl1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_data',
            name='bl1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='bl10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='bl2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='bl3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='bl4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='bl5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='bl6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='bl7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='bl8',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='bl9',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='branch_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='college_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='faculty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='m1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='m10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='m2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='m3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='m4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='m5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='m6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='m7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='m8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='m9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q10',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q6',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q7',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q8',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q9',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='subject_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
