# Generated by Django 5.0.4 on 2024-04-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_subject_data_bl1_alter_subject_data_bl10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_data',
            name='bl11',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subject_data',
            name='bl12',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subject_data',
            name='m11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject_data',
            name='m12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject_data',
            name='q11',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subject_data',
            name='q12',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
