# Generated by Django 5.0.4 on 2024-04-22 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_subject_data_bl11_subject_data_bl12_subject_data_m11_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_data',
            name='bl1',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='bl10',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='bl11',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='bl12',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='bl2',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='bl3',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='bl4',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='bl5',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='bl6',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='bl7',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='bl8',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='bl9',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='m1',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='m10',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='m11',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='m12',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='m2',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='m3',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='m4',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='m5',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='m6',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='m7',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='m8',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='m9',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='q11',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='q12',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='subject_data',
            name='q9',
        ),
        migrations.AddField(
            model_name='subject_data',
            name='number_of_sets',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subject_data',
            name='paper_format',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='MidSemPaperSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(blank=True, max_length=500, null=True)),
                ('q2', models.CharField(blank=True, max_length=500, null=True)),
                ('q3', models.CharField(blank=True, max_length=500, null=True)),
                ('q4', models.CharField(blank=True, max_length=500, null=True)),
                ('q5', models.CharField(blank=True, max_length=500, null=True)),
                ('q6', models.CharField(blank=True, max_length=500, null=True)),
                ('q7', models.CharField(blank=True, max_length=500, null=True)),
                ('q8', models.CharField(blank=True, max_length=500, null=True)),
                ('q9', models.CharField(blank=True, max_length=500, null=True)),
                ('q10', models.CharField(blank=True, max_length=500, null=True)),
                ('q11', models.CharField(blank=True, max_length=500, null=True)),
                ('q12', models.CharField(blank=True, max_length=500, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midsem_paper', to='app.subject_data')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterPaperSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(blank=True, max_length=500, null=True)),
                ('q2', models.CharField(blank=True, max_length=500, null=True)),
                ('q3', models.CharField(blank=True, max_length=500, null=True)),
                ('q4', models.CharField(blank=True, max_length=500, null=True)),
                ('q5', models.CharField(blank=True, max_length=500, null=True)),
                ('q6', models.CharField(blank=True, max_length=500, null=True)),
                ('q7', models.CharField(blank=True, max_length=500, null=True)),
                ('q8', models.CharField(blank=True, max_length=500, null=True)),
                ('q9', models.CharField(blank=True, max_length=500, null=True)),
                ('q10', models.CharField(blank=True, max_length=500, null=True)),
                ('q11', models.CharField(blank=True, max_length=500, null=True)),
                ('q12', models.CharField(blank=True, max_length=500, null=True)),
                ('q13', models.CharField(blank=True, max_length=500, null=True)),
                ('q14', models.CharField(blank=True, max_length=500, null=True)),
                ('q15', models.CharField(blank=True, max_length=500, null=True)),
                ('q16', models.CharField(blank=True, max_length=500, null=True)),
                ('q17', models.CharField(blank=True, max_length=500, null=True)),
                ('q18', models.CharField(blank=True, max_length=500, null=True)),
                ('q19', models.CharField(blank=True, max_length=500, null=True)),
                ('q20', models.CharField(blank=True, max_length=500, null=True)),
                ('q21', models.CharField(blank=True, max_length=500, null=True)),
                ('q22', models.CharField(blank=True, max_length=500, null=True)),
                ('q23', models.CharField(blank=True, max_length=500, null=True)),
                ('q24', models.CharField(blank=True, max_length=500, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_paper', to='app.subject_data')),
            ],
        ),
    ]
