# Generated by Django 5.0.4 on 2024-04-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_subject_data_bl1_remove_subject_data_bl10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterpaperset',
            name='q21',
        ),
        migrations.RemoveField(
            model_name='semesterpaperset',
            name='q22',
        ),
        migrations.RemoveField(
            model_name='semesterpaperset',
            name='q23',
        ),
        migrations.RemoveField(
            model_name='semesterpaperset',
            name='q24',
        ),
    ]
