# Generated by Django 5.0.4 on 2024-04-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_semesterpaperset_q21_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterpaperset',
            name='q21',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='semesterpaperset',
            name='q22',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='semesterpaperset',
            name='q23',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='semesterpaperset',
            name='q24',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subject_data',
            name='marks_format',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
