# Generated by Django 5.0.4 on 2024-04-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_semesterpaperset_q21_semesterpaperset_q22_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_data',
            name='marks_format',
            field=models.CharField(choices=[('6-6-6, 6-6-5', 'Firsttype'), ('9-9, 9-8', 'Secondtype'), ('6-5-4', 'Thirdtype'), ('5-5-5', 'Fourthtype')], default='6-6-6, 6-6-5', max_length=120),
        ),
    ]
