# Generated by Django 5.0.4 on 2024-04-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_subject_data_marks_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_data',
            name='marks_format',
            field=models.CharField(blank=True, choices=[('6-6-6, 6-6-5', 'Six Six Five Endsem'), ('9-9, 9-8', 'Nine Eight Endsem'), ('6-5-4', 'Six Five Four Midsem'), ('5-5-5', 'Five Five Five Midsem')], max_length=120, null=True),
        ),
    ]
